language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
cache: pip
sudo: true
dist: xenial
services:
  - postgresql
  - rabbitmq
addons:
  apt:
    packages:
      - rabbitmq-server
      - python3
      - python3-tk
      - python3-pip
      - python3-numpy
      - python3-h5py
before_install:
  - sudo pip3 install -U pip setuptools
  - sudo pip3 install symmetry-representation
install:
  - pip install -U 'pip<19' wheel setuptools
  - pip install .[dev]
  - reentry scan
env:
  - TEST_TYPE="pre-commit"
  - TEST_TYPE="tests"
script:
  - ./.travis-data/test_script.sh
